from fuzzywuzzy import fuzz

api_answers = [
    "\"At the end of the policy period, the policy shall terminate and can be renewed within the Grace Period of 30 days to maintain continuity of benefits without break in policy. Coverage is not available during the grace period.\"",
    "Pre-existing Disease (Only PEDs declared in the Proposal\nForm and accepted for coverage by the Company shall be\ncovered after 36 months of continuous coverage of continuous coverage of continuous coverage",
    "Yes, this policy covers maternity expenses under Section 3.1.14.\n\nMaternity Expenses means;\na) Medical treatment expenses traceable to childbirth (including complicated deliveries and caesarean sections incurred during Hospitalization);\nb) Expenses towards lawful medical termination of pregnancy during the Policy Period.\n\nExclusions:\nThe Company shall not be liable to make any payment under the cover in respect of Maternity Expenses incurred in connection with or in respect of:\n1. Covered female Insured Person below eighteen (18) years and above forty-five (45) years of age.\n2. Delivery or termination within a Waiting Period of twenty-four (24) months. However, the Waiting Period may be waived only in the case of delivery, miscarriage or abortion induced by accident.\n3. Delivery or lawful medical termination of pregnancy limited to two deliveries or terminations or either has been paid under the Policy and its Renewals.\n4. More than one delivery or lawful medical termination of pregnancy during a single Policy Period.\n5. Maternity Expenses of Surrogate Mother, unless claim is admitted under Section 3.1.15 (Infertility)\n6. Ectopic pregnancy\n7. Pre and post hospitalisation expenses, other than pre and post natal treatment.\nThe female Insured Person should have been continuously covered for at least 24 months before availing this benefit.\nThe New Born Baby shall be automatically covered from birth under the Sum Insured available to the mother during the corresponding Policy Period, for up to 3 months of age. On attaining 3 months of age, the New Born Baby shall be covered only if specifically included in the Policy mid-term and requisite premium paid to the Company.",
    "Two years waiting period\na. Cataract",
    "Yes, the medical expenses for an organ donor are covered under this policy, subject to certain conditions and exclusions.\n\n\"The Company shall indemnify the Medical Expenses incurred in respect of an organ donor’s Hospitalisation during the Policy\nPeriod for harvesting of the organ donated to an Insured Person, provided that:\ni. The organ donation confirms to the Transplantation of Human Organs Act 1994 (and its amendments from time to time)\nii. The organ is used for an Insured Person and the Insured Person has been medically advised to undergo an organ transplant\niii. The Medical Expenses shall be incurred in respect of the organ donor as an in-patient in a Hospital.\niv. Claim has been admitted under In-patient Treatment Section in respect of the Insured Person undergoing the organ\ntransplant.\"\n\nHowever, there are exclusions:\n\n\"The Company shall not be liable to make payment for any claim under this Cover which arises for or in connection with any of the\nfollowing:\ni. Pre-hospitalization Medical Expenses or Post- Hospitalization Medical Expenses of the organ donor.\nii. Costs directly or indirectly associated with the acquisition of the donor’s organ.\niii. Medical Expenses where the organ transplant is experimental or investigational.\niv. Any medical treatment or complication in respect of the donor, consequent to harvesting.\nv. Any expenses related to organ transportation or preservation.\"",
    "On renewal of policies with a term of one year, a NCD of flat 5% shall be allowed on the * base premium, provided claims are not reported in the expiring Policy.\nOn renewal of policies with a term exceeding one year, the NCD amount with respect to each claim free policy year shall be aggregated and allowed on renewal. Aggregate amount of NCD allowed shall not exceed flat 5% of the total base premium for the term of the policy.",
    "Yes, there is a benefit for preventive health check-ups: \"Expenses of health check up shall be reimbursed (irrespective of past claims) at the end of a block of two continuous policy years, provided the Policy has been continuously renewed with the Company without a break. Expenses payable are subject to the limit stated in the Table of Benefits.\"",
    "The provided excerpts do not contain a definition of \"Hospital.\"",
    "\"The Company shall indemnify Medical Expenses incurred for Inpatient Care treatment under Ayurveda, Yoga and Naturopathy, Unani, Siddha and Homeopathy systems of medicines during each Policy Period up to the limit of Sum Insured as specified in the Policy Schedule in any AYUSH Hospital.\"\n\"AYUSH Treatment (as Floater) Up to SI Up to SI Up to SI\"",
    "Yes, for Plan A, \"Room - Up to 1% of SI or actual, whichever is lower ICU – Up to 2% of SI or actual, whichever is lower\" \"* Room/ ICU Charges (per day per insured person) Up to SI Up to SI Up to SI\" \"* The limit shall not apply if the treatment is undergone for a listed procedure in a Preferred Provider Network (PPN) as a package.\n\nThe policy does not specify a cap on room rent for Plan B or Plan C, but it does state that the room rent is capped at 1% of the Sum Insured for Plan A."
]

desired_answers = [
    "A grace period of thirty days is provided for premium payment after the due date to renew or continue the policy without losing continuity benefits.",
    "There is a waiting period of thirty-six (36) months of continuous coverage from the first policy inception for pre-existing diseases and their direct complications to be covered.",
    "Yes, the policy covers maternity expenses, including childbirth and lawful medical termination of pregnancy. To be eligible, the female insured person must have been continuously covered for at least 24 months. The benefit is limited to two deliveries or terminations during the policy period.",
    "The policy has a specific waiting period of two (2) years for cataract surgery.",
    "Yes, the policy indemnifies the medical expenses for the organ donor's hospitalization for the purpose of harvesting the organ, provided the organ is for an insured person and the donation complies with the Transplantation of Human Organs Act, 1994.",
    "A No Claim Discount of 5% on the base premium is offered on renewal for a one-year policy term if no claims were made in the preceding year. The maximum aggregate NCD is capped at 5% of the total base premium.",
    "Yes, the policy reimburses expenses for health check-ups at the end of every block of two continuous policy years, provided the policy has been renewed without a break. The amount is subject to the limits specified in the Table of Benefits.",
    "A hospital is defined as an institution with at least 10 inpatient beds (in towns with a population below ten lakhs) or 15 beds (in all other places), with qualified nursing staff and medical practitioners available 24/7, a fully equipped operation theatre, and which maintains daily records of patients.",
    "The policy covers medical expenses for inpatient treatment under Ayurveda, Yoga, Naturopathy, Unani, Siddha, and Homeopathy systems up to the Sum Insured limit, provided the treatment is taken in an AYUSH Hospital.",
    "Yes, for Plan A, the daily room rent is capped at 1% of the Sum Insured, and ICU charges are capped at 2% of the Sum Insured. These limits do not apply if the treatment is for a listed procedure in a Preferred Provider Network (PPN)."
]

scores = []
for api, desired in zip(api_answers, desired_answers):
    score = fuzz.token_sort_ratio(api, desired)
    scores.append(score)
    print(f"Score: {score}%\nAPI: {api}\nDESIRED: {desired}\n{'-'*60}")

print(f"Average match: {sum(scores)/len(scores):.2f}%")